### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ahouspan** [scythe-io/purple-team-exercise-framework#2]
The linked  pdf file in section (# Cyber Threat Intelligence) seems to be no longer available [ATT&CKing the Status Quo: Threat-Based Adversary Emulation with MITRE ATT&CK](https://www.sans.org/cyber-security-summit/archives/file/summit-archive-1536260992.pdf) 

I've only found this instead: https://www.slideshare.net/KatieNickels/threatbased-adversary-emulation-with-mitre-attck

**Comment by jorgeorchilles** [comment]
Thanks! Fixed it: https://github.com/scythe-io/purple-team-exercise-framework/commit/6b54e1a5b487850c7cea91d7072ea5befc0663a0
