### ISSUE TITLE
Consider adding external references related to the term/concept of Table Top Exercises

### ISSUE THREAD

**Issue by ahouspan** [scythe-io/purple-team-exercise-framework#3]
I wasn't familiar with the term/concept of Table Top Exercises. 
Pls consider adding a reference to something like https://www.mitre.org/sites/default/files/publications/pr_14-3929-cyber-exercise-playbook.pdf or similar. Thanks!

**Comment by jorgeorchilles** [comment]
Will consider adding reference or a glossary to common terms used in the framework.
